# Generated by Django 5.2.1 on 2025-05-14 18:10

import banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to=banners.models.get_random_image_path, verbose_name='Изображение баннера')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('position', models.IntegerField(blank=True, default=0, verbose_name='Позиция')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['position'],
            },
        ),
    ]
