# Generated by Django 5.2.1 on 2025-05-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Project', max_length=255, verbose_name='Название компании')),
                ('email', models.EmailField(default='info@project.ru', max_length=254, verbose_name='Email')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на ВКонтакте')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
                ('company_details', models.TextField(blank=True, help_text='Введите каждый абзац с новой строки', null=True, verbose_name='Детали компании')),
                ('privacy_policy', models.TextField(blank=True, null=True, verbose_name='Политика конфиденциальности')),
                ('terms_of_service', models.TextField(blank=True, null=True, verbose_name='Пользовательское соглашение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Информация о сайте',
                'verbose_name_plural': 'Информация о сайте',
            },
        ),
    ]
