# Generated by Django 5.2.1 on 2025-05-14 18:10

import django.db.models.deletion
import tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('poster', models.ImageField(upload_to=tours.models.Tour._get_upload_path_for_poster, verbose_name='Обложка для карточки')),
                ('cover', models.ImageField(upload_to=tours.models.Tour._get_upload_path_for_cover, verbose_name='Обложка для страницы')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_events', to='events.event', verbose_name='Мероприятие')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_events', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Связь тура и мероприятия',
                'verbose_name_plural': 'Связи туров и мероприятий',
                'unique_together': {('tour', 'event')},
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='events',
            field=models.ManyToManyField(related_name='tours', through='tours.TourEvent', to='events.event', verbose_name='Мероприятия'),
        ),
    ]
